parameters:
#    bookkeeper_manager.example.class: Bookkeeper\ManagerBundle\Example

services:
#    bookkeeper_manager.example:
#        class: %bookkeeper_manager.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
