parameters:
#    book_manager.example.class: Book\ManagerBundle\Example

services:
#    book_manager.example:
#        class: %book_manager.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
